all:
	gcc -o vfork vfork.c
	gcc -o environ environ.c  
	gcc -o execve execve.c  
	gcc -o execve_script execve_script.c  
	gcc -o fork fork.c  
	gcc -o process process.c  
	gcc -o script_invoked script_invoked.c 

clean:
	rm -rf vfork environ execve execve_script fork process script_invoked
